// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rV0yyYmQrQOuK4nvTLL-fE7bdW-eVq0',
    appId: '1:150115670179:web:dddf2227621f0437800716',
    messagingSenderId: '150115670179',
    projectId: 'flutter-sample-98ef1',
    authDomain: 'flutter-sample-98ef1.firebaseapp.com',
    storageBucket: 'flutter-sample-98ef1.appspot.com',
    measurementId: 'G-99CZ2TEGXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQRPFyB5F0YJOvlAkRh9QKSTVM6xusFs',
    appId: '1:150115670179:android:562e628f991c6a7f800716',
    messagingSenderId: '150115670179',
    projectId: 'flutter-sample-98ef1',
    storageBucket: 'flutter-sample-98ef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpNWWVLEwZciWnMMkqQ1-FMiDMAS7s59I',
    appId: '1:150115670179:ios:c8a46db3eba43e25800716',
    messagingSenderId: '150115670179',
    projectId: 'flutter-sample-98ef1',
    storageBucket: 'flutter-sample-98ef1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpNWWVLEwZciWnMMkqQ1-FMiDMAS7s59I',
    appId: '1:150115670179:ios:6e8b60f91a777af2800716',
    messagingSenderId: '150115670179',
    projectId: 'flutter-sample-98ef1',
    storageBucket: 'flutter-sample-98ef1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
